// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZzyL5uHK2EkVaoMjXiPHm8It_XM40hE',
    appId: '1:325765207932:web:de690f3ecb41c9733f36f9',
    messagingSenderId: '325765207932',
    projectId: 'boilerplate-be543',
    authDomain: 'boilerplate-be543.firebaseapp.com',
    storageBucket: 'boilerplate-be543.appspot.com',
    measurementId: 'G-LRVZX8RL9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1xz6WxW1_GggGX0xIDmwEbmS3CsBsy1w',
    appId: '1:325765207932:android:2ab274b3d905459f3f36f9',
    messagingSenderId: '325765207932',
    projectId: 'boilerplate-be543',
    storageBucket: 'boilerplate-be543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9wrwFb1bLul5_wO9qaKvMErnGILt8_tg',
    appId: '1:325765207932:ios:85b5e6147dbec0443f36f9',
    messagingSenderId: '325765207932',
    projectId: 'boilerplate-be543',
    storageBucket: 'boilerplate-be543.appspot.com',
    iosClientId: '325765207932-keola5v4d4c18nefeg0cg7n11rlpb4n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9wrwFb1bLul5_wO9qaKvMErnGILt8_tg',
    appId: '1:325765207932:ios:85b5e6147dbec0443f36f9',
    messagingSenderId: '325765207932',
    projectId: 'boilerplate-be543',
    storageBucket: 'boilerplate-be543.appspot.com',
    iosClientId: '325765207932-keola5v4d4c18nefeg0cg7n11rlpb4n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );
}
